name: Get User Email

on:
  workflow_dispatch:

jobs:
  get_email:
    runs-on: ubuntu-latest
    steps:
      - name: Print User Email
        run: echo "User Email: ${{ github.event.inputs.email }}"
        # If you want to retrieve the email from GitHub API
      - name: Get User Email from GitHub API
        run: |
          USER_EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user | jq -r '.email')
          echo "User Email: $USER_EMAIL"
